# Generated by Django 5.2.11 on 2026-04-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relasto', '0003_alter_property_type_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('agent', 'Agent')], default='buyer', max_length=10),
        ),
    ]
