# Generated by Django 5.2.11 on 2026-04-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relasto', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
