# Generated by Django 5.2.11 on 2026-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relasto', '0015_visitrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='visit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
